name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: .nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
